### ISSUE TITLE
Non-standard `x-forwarded-for`

### ISSUE THREAD

**Issue by juliaqiuxy** [superfly/flyctl#121]
Currently the `x-forwarded-for` header seems to be set to `<originating_ip>, <target_container_ip>` which is odd considering the MDN page for `x-forwarded-for` reads as follows: 

[`If a request goes through multiple proxies, the IP addresses of each successive proxy is listed. This means, the right-most IP address is the IP address of the most recent proxy and the left-most IP address is the IP address of the originating client.
`](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Forwarded-For)

As I understand it correctly the expected value should be `<originating_ip>, <fly_proxy_server_ip>`.

**Comment by jeromegn** [comment]
This is correct. We're appending our proxy IP at the end.

The `<target_container_ip>` you're referring to is not a "container" IP. It is internally assigned to your application, but it's also the IP of all of our servers. This is an "anycast" IP which can be announced from multiple servers at the same time. This IP can reach any of your virtual machines, hosted on us.

Since our servers "listen" for that IP directly, I think it's the correct IP to put in there.

**Comment by mrkurt** [comment]
There's actually a reason for this! If you run `flyctl ips list` you can a see a list of all the IPs your app accepts traffic from. When you parse x-forwarded-for, you can use those as "trusted", find the last instance of your IPs, and then check the preceding IP in the header to see what actually connected to your Fly app.

We also send the "Fly-Client-IP" header to simplify things, no parsing of x-forwarded-for required.

**Comment by mrkurt** [comment]
Feel free to open this back up with more questions.
