### ISSUE TITLE
Error prompt: non interactive

### ISSUE THREAD

**Issue by GNosii** [superfly/flyctl#1534]
**Describe the bug**
Briefly, describe what broke and provide the following details: Trying to create a Fly Postgres cluster fails with an pretty ambigious error message indicating that my terminal is not interactive. I'm using PowerShell and Command Prompt hasn't worked either.

* Windows 11
* flyctl.exe v0.0.441 windows/amd64 Commit: 7a9ec7be BuildDate: 2022-12-16T19:24:02Z

**Command output**

```text
PS C:\Users\***> flyctl pg create -n Pogbase -r scl --verbose --detach
automatically selected personal organization: ***
For pricing information visit: https://fly.io/docs/about/pricing/#postgresql-clustersError prompt: non interactive
```

**Comment by ndarilek** [comment]
Are you still able to replicate this on the latest flyctl release? I fixed this at some point last month but am not sure when/if the fix was released, though I assume it should have been by now.

**Comment by ndarilek** [comment]
I believe this should be fixed. I traced all calls from the previously-failing function, and they now either lead to their Windows equivalents or use our Windows-specific wrapper. I've also not encountered this error since, whereas before it happened with just about every command I tried.

If you're still able to replicate, please re-open with a text-based transcript of the offending session and I'll fix it.

Thanks!
