### ISSUE TITLE
pause/resume using wrong app

### ISSUE THREAD

**Issue by michaeldwan** [superfly/flyctl#175]
Running these commands in a directory containing a fly.toml file for app `damp-fire-3810` is operating on the app from the config rather than the arg:
```
$ flyctl apps pause ruby-example
damp-fire-3810 is now running
$ flyctl apps resume
damp-fire-3810 is now dead
```

(the wrong status will be fixed tomorrow)

**Comment by codepope** [comment]
Initial triage - pause resume are using appRequired in the command builder but this only means that it gets the -a and -c flags added. It doesn't require a named app in the command line. Will add code to enable a named app on the command line to override the -a and -c settings.

**Comment by codepope** [comment]
New args processor (only works with commands with no extra args). If there is a single extra arg, it is used as appname, if not, it falls back to the config file, if no config file, errors out. There is no -a flag (because its being specified inline) but -c flag to can point to a specific config file. Now in for review.

**Comment by codepope** [comment]
Closing issue for now as fix in in the current betas. Feedback as a bug on the beta releases.
