### ISSUE TITLE
flyctl certs create should inform users of next steps better

### ISSUE THREAD

**Issue by codepope** [superfly/flyctl#239]
This point in the UX is complex and the Flyctl response should give better guidance.

**Comment by mrkurt** [comment]
Braindump on certificate verification, some example Ruby we use, and some things that break it.

*DNS verification*: requires a CNAME to us: `_acme-challenge.example.com`, which we use to keep a TXT record updated. We check for the cname specifically with this Ruby:
```ruby
    h = @hostname
    if h.starts_with?("*.")
      h = h.sub(/^\*\./, '')
    end
    record = dns_client.getresource("_acme-challenge.#{h}", Resolv::DNS::Resource::IN::CNAME)
    return record.name.to_s === flydns_record # example.com.<uniq>.flydns.net
```

*ALPN verification*: requires that the hostname resolve to an app's ipv6 address. This can be done with either a CNAME (since it aliases all the things) or an AAAA record (required for an apex record). We just do a recursive DNS query to check for this, and don't pay any attention to whether it's a CNAME or not.

*SOA record*: we lookup the SOA record and query that server for all our checks.

*Things that break certificates*

* Some domains have a CAA record that prevents us from issuing a certificate: https://community.letsencrypt.org/t/caa-record-prevents-issuance/95688
* Some have a TXT record at `_acme-challenge.example.com`, that will typically get returned before the CNAME
* Lots of people add an A record but no AAAA record for apex domains
* Sometimes the SOA server doesn't respond to queries, it's annoying

**Comment by codepope** [comment]
Implementation is now on flyctl 0.0.138-beta-1
