### ISSUE TITLE
Completions only exist for flyctl, not fly

### ISSUE THREAD

**Issue by codepope** [superfly/flyctl#320]

**Comment by codepope** [comment]
Dug a bit on this issue. Fixing it is blocked by Cobra not having proper zsh support in place until 1.1.0. Closing to return to it when that happens.

**Comment by teutat3s** [comment]
I hope it's okay to necropost in this closed issue.

I came across this while using the packaged `flyctl` from [nixpkgs](https://search.nixos.org/packages?channel=unstable&show=flyctl&from=0&size=50&sort=relevance&type=packages&query=flyctl) (version `0.0.450`). 

`flyctl TAB` correctly starts completion in `zsh` and `bash`, but typing `fly TAB` doesn't do anything in either shell. Could you confirm if this is reproducible on your end? Otherwise this might be a packaging issue that I'd like to fix upstream.
