### ISSUE TITLE
Allow Using Ephemeral Machines For Health Checks

### ISSUE THREAD

**Issue by benbjohnson** [superfly/flyctl#3233]
We could allow trust checks by running a custom ephemeral machine, where if the machine returns 0 the trust check passes, and otherwise it failed. 

This would be useful for doing more complex health checks, like making sure signup functionality continues to work after a deployment.

**Comment by benbjohnson** [comment]
@billyb2 Can you expand on what the workflow for this would look like? Is it something we could use `fly m run` for instead?

**Comment by billyb2** [comment]
I just mean that basically, `flyctl` after deploying the machine but before marking it as available (or uncordoning or whatever), spawns a new machine with `fly m run --autodestroy`. If that machine exits and returns 0, then the machine passed the health check. Otherwise, it didn't. This is especially useful for things like bluegreen deploys.
