### ISSUE TITLE
GitHub Codespaces Install Incomplete

### ISSUE THREAD

**Issue by Skillz4Killz** [superfly/flyctl#340]
https://fly.io/docs/getting-started/installing-flyctl/#linux

```shell
codespace ➜ ~/workspace/hellodeno-buildpack (master ✗) $ curl -L https://fly.io/install.sh | sh
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  2355    0  2355    0     0  27068      0 --:--:-- --:--:-- --:--:-- 27068
######################################################################## 100.0%
flyctl 0.0.154
Flyctl/Fly was installed successfully to /home/codespace/.fly/bin/flyctl
Run 'flyctl --help' to get started
codespace ➜ ~/workspace/hellodeno-buildpack (master ✗) $ flyctl
bash: flyctl: command not found
```

**Comment by codepope** [comment]
That's interesting, it seems the codespaces dotfiles setup, which changes the behavior (apparently) of "command" in bash. I'll have a dig in on this because the obvious work around (as per the instructions that weren't displays):

```
Manually add the directory to your $HOME/.bash_profile (or similar)
  export FLYCTL_INSTALL="/home/codespace/.fly"
  export PATH="$FLYCTL_INSTALL/bin:$PATH"
Run '/home/codespace/.fly/bin/flyctl --help' to get started
```

don't stick because with no "dotfiles" repo, Codespaces overrides all the .file configuration with its own "default Linux" configuration. (see https://docs.github.com/en/free-pro-team@latest/github/developing-online-with-codespaces/personalizing-codespaces-for-your-account)

Thanks for letting us know - we'd checked out codespaces earlier in its life and things appeared to be working fine but it seems thats no longer the case.
