### ISSUE TITLE
Add setting to always use remote builder, even when docker is running

### ISSUE THREAD

**Issue by mrkurt** [superfly/flyctl#430]
Docker can be problematic on m1 Macs, and there are some cases where it makes sense to have Docker running locally but use remote builds for Fly.

`fly deploy --remote-only` works just fine, but it would be nice to be able to configure a system to default to `--remote-only`. Can we have a `FLY_BUILD_REMOTE_ONLY` environment variable for this?

**Comment by jsierles** [comment]
Why not make remote the default?

**Comment by mik3y** [comment]
Other than the M1 issue, I've found a couple situations where I always prefer remote build: e.g. working from a plane, rural/crappy internet, etc.

Remote is preferable here because of Docker Stuff: while I might only have a few kb of code (docker context), the build itself might suck down gigs of layers to get there.

I'd be happy to submit a patch for this - could use a pointer or preference on approach, if it's a viable idea. Is exposing an env var the way to go..? (Is there an app-unspecific `.flyctrlrc` where this kind of preference could fit the bill..?)

**Comment by kzys** [comment]
Resolving? It is default now.
