### ISSUE TITLE
Specify Dockerfile for deploy

### ISSUE THREAD

**Issue by mrkurt** [superfly/flyctl#46]
Is there a way to specify a Dockerfile to use for build other than just pointing to a subdir?

**Comment by michaeldwan** [comment]
0.0.110 supports this now: `flyctl deploy --dockerfile ./path/to/Dockerfile`

Here's how to deploy a subdirectory in a monorepo that needs sibling directories at build time:

```
flyctl deploy --config app/fly.toml --dockerfile app/Dockerfile .
```

**Comment by 0az** [comment]
I don't think flyctl currently passes it to the Docker daemon. Tested it with a `fly.Dockerfile`, which failed with a BuildKit error, indicating that it's reading the version that didn't have those stripped.

This is a local build only issue, as remote builds such as `flyctl deploy --remote-only --dockerfile ./fly.Dockerfile` do not error out, whereas the version that drops the `--dockerfile` correctly errors, due to the usage of BuildKit's cache mount.
