### ISSUE TITLE
Redis writes across regions are erratic

### ISSUE THREAD

**Issue by codepope** [superfly/flyctl#67]
Testing on regionping app (distributed heartbeat writes) sees writes not making it to all other nodes, in some cases for some time.

Recreate by deploying regionping, scaling to multiple regions, then follow the logs as it writes the ping and follow the regionping UI as it is updated over time.

**Comment by mrkurt** [comment]
@michaeldwan I feel like this is fixed?

**Comment by codepope** [comment]
I shall awaken the test rig….

**Comment by gregmsanderson** [comment]
Since this is still open, I assume it is still an issue?

I've been trying some cache deleting, and assuming I'm doing it right (selecting database 1) the cache is not being deleted.

It's hard to debug because the logs are about half an hour delayed currently so can't see what it is doing behind the scenes. I'm also having to use the redis URL of another app to add another layer of confusion. But from what I can see, currently a cache delete command isn't clearing across regions.
