### ISSUE TITLE
flyctl secrets unset does not appear to unset

### ISSUE THREAD

**Issue by codepope** [superfly/flyctl#96]
With any appliction, setting a secret works, but unsetting a secret does not visibly work.

Set up application which reports state of MYTEST env var. Deploy app and set env var. Var shows value and env var is set. `flyctl secrets list` shows entry with a particular digest value.

Unset MYTEST and repeat process. Var is not set and no value is retrievable *BUT* `flyctl secrets list` shows secret is set with the same digest value as before.

So the variable has been removed from the runtime environment but is misreported as still existing and with its old value (via the digest).

**Comment by juliaqiuxy** [comment]
Why set visibility on a secret rather than remove it when it's unset? Is it because the controller should be able to rollback to the previous state if the deployment happens to fail? Can we assume the secret will be permanently deleted if the deployment succeeds? Form a UX standpoint, it would be great to have a status column in the `flyctl secrets list` output make this clearer to the user. The less magic, the better.

**Comment by mrkurt** [comment]
@juliaqiuxy agreed (just saw your comment).

We just deployed a change that will only show the _actively_ in use secrets for a given app. It would be nice to let people see their secrets history as well, which we can do separately.
